kind: ConfigMap
apiVersion: v1
metadata:
  name: mongo
data:
  mongodb.conf: |-
    storage:
      dbPath: /data/db
      journal:
        enabled: true
      directoryPerDB: false
    # where to write logging data
    systemLog:
      destination: file
      quiet: false
      logAppend: true
      logRotate: reopen
      path: /opt/bitnami/mongodb/logs/mongodb.log
      verbosity: 0
    # network interfaces
    net:
      port: 27017
      unixDomainSocket:
        enabled: true
        pathPrefix: /opt/bitnami/mongodb/tmp
      ipv6: false
      bindIpAll: true
    # replica set options
    #replication:
      #replSetName: replicaset
      #enableMajorityReadConcern: true
    # process management options
    processManagement:
       fork: false
       pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
    # set parameter options
    setParameter:
       enableLocalhostAuthBypass: true
    # security options
    security:
      authorization: disabled
      #keyFile: /opt/bitnami/mongodb/conf/keyfile
